---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj1-poi-gateway-app-repo
  namespace: assemble-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/backstage-mh5sz/ryanj1-gateway-gitops